### ISSUE TITLE
Can you please create a PR in bombardier-gif repo?

### ISSUE THREAD

**Issue by bombardier-gif** [vishalv26/covid-vaccine-booking#2]
This will benefit more users so that they dont have to jump between pallupz, then discover bombardier and then vishalv26

Or you could also create a section in my readme, leading to your repo.

 I am happy to incorporate any of your preference.

**Comment by vishalv26** [comment]
Unfortunately, My version differs from yours in many way. So sending PR would be pointless. Too much of a work for you while merging. And, there is no way i can fork the repo twice. The best i could do is add your version in a separate folder and keep it on auto sync so that it will stay updated whenever you merge any changes. Can you add the link to this version on your `How to run on windows` section? Helps? Open for suggestions
